# Generated by Django 5.0.6 on 2024-05-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='followed_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='following_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
