# Generated by Django 5.0.6 on 2024-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_followed_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mssv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
