# Generated by Django 5.0.6 on 2024-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_danhgia_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
