# Generated by Django 5.0.6 on 2024-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_danhgia_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='nguoidanhgia',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
